### PR TITLE
AMS-2: Dockerizing frontend

### PR DESCRIPTION
**Pull request by MatiasMinchaca**
#### The Dockerfile is created in the frontend folder:
it creates an image by copying files from that folder to docker using the dockerfile commands
#### docker-compose.yml is modified:
it adding the frontend service that links the dockerfile to build the container

### Feature changes 
After running the command:
`$ docker-compose up -d`   
you will be able to view the frontend on [http://localhost:3000/](http://localhost:3000/)

### CODE REVIEW

**Review by eddymdz — CHANGES_REQUESTED** [review]
@MatiasMinchaca please use the latest stable version of NodeJS

**Comment by MatiasMinchaca** [comment]
@eddymdz
 There is a compatibility issue between the 'node-sass' dependency, NodeJS and nuxtjs. That's why I used the 14-slim version of node in docker
#### I was testing between the different versions but to use a newer version of NodeJS it is necessary to update the entire frontend

**Comment by eddymdz** [comment]
@MatiasMinchaca update node-sass

**Comment by eddymdz** [comment]
@MatiasMinchaca I'm still wating for this

**Comment by MatiasMinchaca** [comment]
@eddymdz I have not managed to find a solution, since there are incompatibility problems between node-sass, sass-loader and NodeJS
For the moments, it remains to use NodeJS 14-slim until the root of that problem is well found

[https://www.npmjs.com/package/node-sass](https://www.npmjs.com/package/node-sass)

**Pull request merged**
